const Actions = {
  FETCH_EVENTS: "EVENTS/FETCH_EVENTS",
  SET_EVENTS: "EVENTS/SET_EVENTS",
  FETCH_MORE_EVENTS: "EVENTS/FETCH_MORE_EVENTS",
  SET_MORE_EVENTS: "EVENTS/SET_MORE_EVENTS",
  SET_LIMIT: "EVENTS/SET_LIMIT",
  SET_OFFSET: "EVENTS/SET_OFFSET",
  SET_VARIANT: "EVENTS/SET_VARIANT",
  RESET_OPTIONS: "EVENTS/RESET_OPTIONS",
  UPDATE_COLUMNS: "EVENTS/UPDATE_COLUMNS",
  SET_SORT_DATA: "EVENTS/SET_SORT_DATA",
  SET_SORT_DATA_COLUMNS: "EVENTS/SET_SORT_DATA_COLUMNS",
  SET_TIME_MODE: "EVENTS/SET_TIME_MODE",
};

export default Actions;
